// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlBOXhKOylW5t7ErQKnclMCCiKDZJGWyg',
    appId: '1:139836106124:web:23ba3aaf9e88e65e3e22a9',
    messagingSenderId: '139836106124',
    projectId: 'ideaboard-15292',
    authDomain: 'ideaboard-15292.firebaseapp.com',
    storageBucket: 'ideaboard-15292.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs15-c89fHw7jW8JARt9gKqzWvfk_SJk8',
    appId: '1:139836106124:android:d55260ac59127a4c3e22a9',
    messagingSenderId: '139836106124',
    projectId: 'ideaboard-15292',
    storageBucket: 'ideaboard-15292.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCYlF4FJ2eA44D37vkjUMrUqeJcuzDGcA',
    appId: '1:139836106124:ios:b47cd799fabffdc73e22a9',
    messagingSenderId: '139836106124',
    projectId: 'ideaboard-15292',
    storageBucket: 'ideaboard-15292.firebasestorage.app',
    iosBundleId: 'com.example.idea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCYlF4FJ2eA44D37vkjUMrUqeJcuzDGcA',
    appId: '1:139836106124:ios:b47cd799fabffdc73e22a9',
    messagingSenderId: '139836106124',
    projectId: 'ideaboard-15292',
    storageBucket: 'ideaboard-15292.firebasestorage.app',
    iosBundleId: 'com.example.idea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlBOXhKOylW5t7ErQKnclMCCiKDZJGWyg',
    appId: '1:139836106124:web:79c3ad60b00f53b73e22a9',
    messagingSenderId: '139836106124',
    projectId: 'ideaboard-15292',
    authDomain: 'ideaboard-15292.firebaseapp.com',
    storageBucket: 'ideaboard-15292.firebasestorage.app',
  );
}
